src/main/java/de/qabel/desktop/QblMain.java

Updates the module to the current Qabel-Core version.
For now it works like before, more functionality is not implemented.

Adapt to the Qabel Core version

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to https://github.com/Qabel/qabel-core/pull/329
Closes #13

Adapted to refactored drop actor

---

.travis.yml

Adds a similar travis.yml like in qabel-core
Closes #12

Adds a travis.yml

---

.gitmodules

Removed submodule qabel-core

---

README.md
src/main/java/de/qabel/desktop/QblMain.java

Adapt refactored module manager

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to URL to URI change

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to https://github.com/Qabel/qabel-core/pull/356

Adapt to refactored Persistence

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to https://github.com/Qabel/qabel-core/pull/371

Adapt to Contact alias

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to: https://github.com/Qabel/qabel-core/pull/375

Adapt to "Added exception when opening persistence with wrong password"

---

.travis.yml

At last faster testing also for qabel-desktop.

Migrate to Travis container-based infrastructure

---

src/main/java/de/qabel/desktop/QblMain.java

Adapt to https://github.com/Qabel/qabel-core/pull/427

Added PBKDF2 rounds to persistence initialisation

---

src/main/java/com/airhacks/afterburner/views/QabelFXMLView.java
src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/ui/LayoutController.java
src/main/java/de/qabel/desktop/ui/LayoutView.java
src/main/java/de/qabel/desktop/ui/accounting/AccountingView.java
src/main/java/de/qabel/desktop/ui/accounting/item/AccountingItemController.java
src/main/java/de/qabel/desktop/ui/accounting/item/AccountingItemView.java
src/main/resources/de/qabel/desktop/ui/accounting/accounting.fxml
src/main/resources/de/qabel/desktop/ui/accounting/item/accountingitem.css
src/main/resources/de/qabel/desktop/ui/accounting/item/accountingitem.fxml
src/main/resources/de/qabel/desktop/ui/layout.css
src/main/resources/de/qabel/desktop/ui/layout.fxml
src/main/resources/main.css

navi / base layout and integrationpoint for future views

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/de/qabel/desktop/config/BoxSyncConfig.java
src/main/java/de/qabel/desktop/config/ClientConfiguration.java
src/main/java/de/qabel/desktop/config/DefaultBoxSyncConfig.java
src/main/java/de/qabel/desktop/config/DefaultClientConfiguration.java
src/main/java/de/qabel/desktop/repository/persistence/PersistenceClientConfigurationRepository.java
src/main/java/de/qabel/desktop/repository/persistence/PersistentBoxSyncConfig.java
src/main/java/de/qabel/desktop/repository/persistence/PersistentClientConfiguration.java
src/main/java/de/qabel/desktop/ui/LayoutController.java
src/main/java/de/qabel/desktop/ui/sync/SyncController.java
src/main/java/de/qabel/desktop/ui/sync/SyncView.java
src/main/java/de/qabel/desktop/ui/sync/item/SyncItemController.java
src/main/java/de/qabel/desktop/ui/sync/item/SyncItemView.java
src/main/resources/de/qabel/desktop/ui/layout.css
src/main/resources/de/qabel/desktop/ui/layout.fxml
src/main/resources/de/qabel/desktop/ui/sync/item/syncitem.css
src/main/resources/de/qabel/desktop/ui/sync/item/syncitem.fxml
src/main/resources/de/qabel/desktop/ui/sync/sync.css
src/main/resources/de/qabel/desktop/ui/sync/sync.fxml
src/test-gui/java/de/qabel/desktop/ui/AbstractControllerGUITest.java
src/test-gui/java/de/qabel/desktop/ui/AbstractGuiTest.java
src/test/java/de/qabel/desktop/config/DefaultBoxSyncConfigTest.java
src/test/java/de/qabel/desktop/repository/persistence/PersistenceClientConfigurationRepositoryTest.java
src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java
src/test/java/de/qabel/desktop/ui/remotefs/LazyBoxFolderTreeItemTest.java

working on #46 
looks like this
The folder-icon will be replaced by the identities avatar to show which identity the sync is assigned to.
The "create new sync" dialog/wizard is currently missing

[WIP] #46 Sync

---

.gitignore
src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/ui/LayoutController.java
src/main/java/de/qabel/desktop/ui/actionlog/ActionlogController.java
src/main/java/de/qabel/desktop/ui/actionlog/ActionlogView.java
src/main/java/de/qabel/desktop/ui/actionlog/item/ActionlogItem.java
src/main/java/de/qabel/desktop/ui/actionlog/item/ActionlogItemView.java
src/main/java/de/qabel/desktop/ui/actionlog/item/MyActionlogItemController.java
src/main/java/de/qabel/desktop/ui/actionlog/item/MyActionlogItemView.java
src/main/java/de/qabel/desktop/ui/actionlog/item/OtherActionlogItemController.java
src/main/java/de/qabel/desktop/ui/actionlog/item/OtherActionlogItemView.java
src/main/java/de/qabel/desktop/ui/actionlog/item/OtherTextWrapper.java
src/main/resources/de/qabel/desktop/ui/accounting/accounting.fxml
src/main/resources/de/qabel/desktop/ui/actionlog/actionlog.fxml
src/main/resources/de/qabel/desktop/ui/actionlog/item/myactionlogitem.fxml
src/main/resources/de/qabel/desktop/ui/actionlog/item/otheractionlogitem.fxml
src/main/resources/de/qabel/desktop/ui/contact/contact.fxml
src/main/resources/de/qabel/desktop/ui/layout.fxml
src/main/resources/main.css
src/main/resources/ui.properties
src/main/resources/ui_de_DE.properties
src/main/resources/ui_te_ST.properties
src/test/java/de/qabel/desktop/ui/actionlog/ActionlogControllerTest.java

actionlog ui without functions

---

src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/cellValueFactory/BoxObjectCellValueFactory.java
src/main/java/de/qabel/desktop/config/ClientConfiguration.java
src/main/java/de/qabel/desktop/config/DefaultClientConfiguration.java
src/main/java/de/qabel/desktop/config/factory/LocalBoxVolumeFactory.java
src/main/java/de/qabel/desktop/config/factory/S3BoxVolumeFactory.java
src/main/java/de/qabel/desktop/repository/persistence/PersistenceClientConfigurationRepository.java
src/main/java/de/qabel/desktop/repository/persistence/PersistentClientConfiguration.java
src/main/java/de/qabel/desktop/storage/DirectoryMetadata.java
src/main/java/de/qabel/desktop/storage/FolderNavigation.java
src/main/java/de/qabel/desktop/storage/IndexNavigation.java
src/main/java/de/qabel/desktop/storage/LocalReadBackend.java
src/main/java/de/qabel/desktop/storage/S3ReadBackend.java
src/main/java/de/qabel/desktop/storage/StorageDownload.java
src/main/java/de/qabel/desktop/storage/StorageReadBackend.java
src/main/java/de/qabel/desktop/ui/remotefs/LazyBoxFolderTreeItem.java
src/test/java/de/qabel/desktop/daemon/management/DefaultTransferManagerTest.java
src/test/java/de/qabel/desktop/repository/persistence/PersistenceClientConfigurationRepositoryTest.java

+changed S3 read access to ETag

#36 deviceId

---

src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/daemon/management/DefaultTransferManager.java
src/main/java/de/qabel/desktop/ui/LayoutController.java
src/main/java/de/qabel/desktop/ui/accounting/AccountingController.java
src/main/java/de/qabel/desktop/ui/accounting/item/AccountingItemController.java
src/main/resources/de/qabel/desktop/ui/accounting/accounting.fxml
src/main/resources/de/qabel/desktop/ui/accounting/item/accountingitem.css
src/main/resources/de/qabel/desktop/ui/accounting/item/accountingitem.fxml
src/main/resources/de/qabel/desktop/ui/layout.css
src/main/resources/de/qabel/desktop/ui/layout.fxml
src/main/resources/main.css
src/test/java/de/qabel/desktop/ui/accounting/AccountingControllerTest.java
src/test/java/de/qabel/desktop/ui/accounting/item/AccountingItemControllerTest.java

+ disable unusable buttons in AccountingView

[UX] navi header makeover

---

src/main/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncer.java
src/main/java/de/qabel/desktop/daemon/sync/worker/index/SyncIndex.java
src/main/java/de/qabel/desktop/ui/accounting/AccountingController.java

fixes root sync and general directory syncs.
There are still issues with conflicts and timings but they will be addressed in #45

#135 syncHotfix

---

.editorconfig
.gitignore
README.md
build.gradle
src/main/java/de/qabel/desktop/repository/ContactRepository.java
src/main/java/de/qabel/desktop/repository/persistence/PersistenceContactRepository.java
src/main/java/de/qabel/desktop/ui/contact/ContactController.java
src/main/java/de/qabel/desktop/ui/remotefs/RemoteFileDetailsController.java
src/test-gui/java/de/qabel/desktop/ui/contact/ContactGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/remotefs/RemoteFSGuiTest.java
src/test/java/de/qabel/desktop/repository/Stub/InMemoryContactRepository.java
src/test/java/de/qabel/desktop/ui/contact/ContactControllerTest.java

allows to pass a `release` version to gradle in order to build an application that checks for the correct version without additional modifications

gradle release option

---

src/main/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncer.java
src/test/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncerTest.java

fixes #210 `//next time I'll succeed in writing this to the commit message ;)`

#210 prevent sync to change anything locally outside the sync dir

---

src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/daemon/sync/blacklist/Blacklist.java
src/main/java/de/qabel/desktop/daemon/sync/blacklist/PatternBlacklist.java
src/main/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncer.java
src/test/java/de/qabel/desktop/daemon/sync/blacklist/FileBasedSyncBlacklistTest.java
src/test/java/de/qabel/desktop/daemon/sync/blacklist/PatternBlacklistTest.java
src/test/java/de/qabel/desktop/daemon/sync/worker/BlacklistSpy.java
src/test/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncerTest.java
src/test/java/de/qabel/desktop/ui/connector/HttpDropConnectorTest.java

also fixes #189 if `test-drop.qabel.de` is the correct url because the old server doesn't work anymore

fixes #109 ignore folders that violate special char patterns

---

src/main/resources/de/qabel/desktop/ui/about/about.fxml
src/main/resources/ui.properties
src/main/resources/ui_de_DE.properties

#261 added setup tools to about dialog

---

src/main/resources/de/qabel/desktop/ui/about/about.fxml

#280 added icon and font licenses

---

src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/ServiceFactory.java
src/main/java/de/qabel/desktop/config/factory/DropUrlGenerator.java
src/main/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncer.java
src/main/java/de/qabel/desktop/daemon/sync/worker/Syncer.java
src/main/java/de/qabel/desktop/daemon/sync/worker/TreeWatcher.java
src/main/java/de/qabel/desktop/inject/Create.java
src/main/java/de/qabel/desktop/inject/Creates.java
src/main/java/de/qabel/desktop/inject/DefaultServiceFactory.java
src/main/java/de/qabel/desktop/inject/DesktopServices.java
src/main/java/de/qabel/desktop/inject/StaticDesktopServiceFactory.java
src/main/java/de/qabel/desktop/inject/config/RuntimeConfiguration.java
src/main/java/de/qabel/desktop/inject/config/StaticRuntimeConfiguration.java
src/main/java/de/qabel/desktop/ui/inject/RecursiveInjectionInstanceSupplier.java
src/main/resources/de/qabel/desktop/ui/sync/item/syncitem.fxml
src/test/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncerTest.java
src/test/java/de/qabel/desktop/daemon/sync/worker/FakeSyncer.java
src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java
src/test/java/de/qabel/desktop/ui/inject/RecursiveInjectionInstanceSupplierTest.java

main part (last commit) extracts the whole "DIContainer" (aka HashMap) from the main DesktopClient to it's own class (StaticDesktopServiceFactory) that is abstracted to two sides:
ServiceFactory abstracts the generic "get('serviceName')" part and
DesktopServices abstracts the whole "getIdentityRepository" etc. stuff
all wiring is now lazy

preparation for #182 (extraction of DI container)

---

src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/config/factory/BlockBoxVolumeFactory.java
src/main/java/de/qabel/desktop/inject/DesktopServices.java
src/main/java/de/qabel/desktop/inject/StaticDesktopServiceFactory.java
src/main/java/de/qabel/desktop/storage/AbstractNavigation.java
src/main/java/de/qabel/desktop/storage/BoxVolume.java
src/main/java/de/qabel/desktop/storage/DefaultIndexNavigation.java
src/main/java/de/qabel/desktop/storage/DeleteOnCloseFileInputStream.java
src/main/java/de/qabel/desktop/storage/DirectoryMetadata.java
src/main/java/de/qabel/desktop/storage/FileMetadata.java
src/main/java/de/qabel/desktop/storage/FolderNavigation.java
src/test-gui/java/de/qabel/desktop/ui/AbstractPage.java
src/test/java/de/qabel/desktop/storage/BoxVolumeBlockTest.java
src/test/java/de/qabel/desktop/storage/BoxVolumeTest.java
src/test/java/de/qabel/desktop/storage/DeleteOnCloseFileInputStreamTest.java
src/test/java/de/qabel/desktop/storage/cache/CachedBoxVolumeTest.java

#311 delete tmp files for up- and downloads

---

src/test-gui/java/de/qabel/desktop/ui/AbstractGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/InputDialogPage.java
src/test-gui/java/de/qabel/desktop/ui/accounting/AccountingGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/accounting/AccountingPage.java
src/test-gui/java/de/qabel/desktop/ui/accounting/item/AccountingItemGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/accounting/item/AccountingItemPage.java
src/test-gui/java/de/qabel/desktop/ui/accounting/login/LoginGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/accounting/login/LoginPage.java
src/test-gui/java/de/qabel/desktop/ui/accounting/login/RecoverPasswordUiTest.java
src/test-gui/java/de/qabel/desktop/ui/remotefs/RemoteBrowserPage.java
src/test-gui/java/de/qabel/desktop/ui/remotefs/RemoteFSGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/sync/SyncControllerGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/sync/SyncPage.java
src/test-gui/java/de/qabel/desktop/ui/sync/item/SyncItemControllerGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/sync/setup/SyncSetupGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/sync/setup/SyncSetupPage.java

...for all GUI tests to allow for continued maintainance and readability of tests.
Only gui test refactoring. The last commits with tabs, I promise ;)

extraction of page objects

---

.gitignore
Vagrantfile
src/main/java/de/qabel/desktop/DesktopClient.java
src/main/java/de/qabel/desktop/daemon/drop/DropDaemon.java

this is why 0.6.0 is skipped in favor of 0.6.1

Mkconfigdir

---

src/main/java/de/qabel/desktop/ui/tray/QabelTray.java

caused freezes in other parts of the application

removed tray remove on exit

---

src/main/resources/main.css

#198 - changed the color of tooltip

---

src/main/java/de/qabel/desktop/DesktopClient.java

60s according to aws` recommendation http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-jvm-ttl.html

#328 aws friendly dns caching

---

src/main/java/de/qabel/desktop/cellValueFactory/BoxObjectCellValueFactory.java
src/test/java/de/qabel/desktop/cellValueFactory/BoxObjectCellValueFactoryTest.java

#206 - adjustments in file size and date format

---

src/main/java/de/qabel/desktop/daemon/drop/DropDaemon.java
src/test/java/de/qabel/desktop/daemon/drop/DropDaemonTest.java
src/test/java/de/qabel/desktop/repository/inmemory/InMemoryHttpDropConnector.java

#363 keep DropDaemon alive on error

---

src/main/java/de/qabel/desktop/daemon/drop/DropDaemon.java
src/main/java/de/qabel/desktop/inject/RuntimeDesktopServiceFactory.java
src/test/java/de/qabel/desktop/daemon/drop/DropDaemonTest.java
src/test/java/de/qabel/desktop/repository/Stub/StubDropMessageRepository.java
src/test/java/de/qabel/desktop/repository/inmemory/InMemoryHttpDropConnector.java

Actually, the one daemon only iterates over all identities. No need for multiple daemons imho.
+made the StubDropMessageRepository (probably) fully functional
closed #129

#129 check drops of all identities

---

src/main/java/de/qabel/desktop/ui/LayoutController.java

solves #356 - naviItem needs to be set managed and visible in the same way to prevent layout bugs

Layout Navigation Breaks Ui

---

src/main/resources/main.css

added scrollbar in the filebrowser

---

src/main/java/de/qabel/desktop/DesktopClientGui.java

start client minimized / iconified if an account and identity exists

---

dist/resources/launch.properties
launch.properties.dist
src/main/java/de/qabel/desktop/LaunchConfigurationReader.java
src/main/java/de/qabel/desktop/config/LaunchConfig.java
src/main/java/de/qabel/desktop/hockeyapp/HockeyAppRequestBuilder.java
src/main/java/de/qabel/desktop/inject/RuntimeDesktopServiceFactory.java
src/main/java/de/qabel/desktop/inject/config/RuntimeConfiguration.java
src/main/java/de/qabel/desktop/inject/config/StaticRuntimeConfiguration.java
src/main/resources/launch.properties
src/test/java/de/qabel/desktop/LaunchConfigurationReaderTest.java
src/test/java/de/qabel/desktop/hockeyapp/CrashReporterClientTest.java
src/test/java/de/qabel/desktop/hockeyapp/FeedbackClientTest.java
src/test/java/de/qabel/desktop/hockeyapp/HockeyAppRequestBuilderTest.java
src/test/java/de/qabel/desktop/hockeyapp/VersionClientTest.java

make crashreport URL configurable

---

src/main/java/de/qabel/desktop/DesktopClientGui.java
src/test/java/de/qabel/desktop/AbstractKernelTest.java
src/test/java/de/qabel/desktop/DesktopClientGuiTest.java
src/test/java/de/qabel/desktop/KernelTest.java
src/test/java/de/qabel/desktop/TestKernel.java
src/test/java/de/qabel/desktop/util/KernelTestUtils.java

starMinimized

---

src/main/java/de/qabel/desktop/DesktopClientGui.java
src/test/java/de/qabel/desktop/DesktopClientGuiTest.java

only apply's if logged in
resolves #326

minimize on loggedin state

---

src/main/resources/main.css

An avatar should be round. This avatar should be round.
This avatar is now round again!

Make the avatar round again!

---

src/main/java/de/qabel/desktop/util/QuotaUtil.java
src/main/resources/ui.properties
src/main/resources/ui_de_DE.properties
src/main/resources/ui_te_ST.properties
src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java
src/test/java/de/qabel/desktop/ui/LayoutControllerTest.java
src/test/java/de/qabel/desktop/util/QuotaUtilTest.java

show used quota instead of free quota

---

src/main/java/de/qabel/desktop/DesktopClientGui.java
src/main/java/de/qabel/desktop/config/ClientConfig.java
src/main/java/de/qabel/desktop/config/DefaultClientConfiguration.java
src/main/java/de/qabel/desktop/config/RepositoryBasedClientConfig.java
src/main/java/de/qabel/desktop/ui/LayoutController.java
src/main/java/de/qabel/desktop/ui/about/AboutController.java
src/main/resources/de/qabel/desktop/ui/about/about.fxml
src/test-gui/java/de/qabel/desktop/ui/LayoutGuiTest.java
src/test-gui/java/de/qabel/desktop/ui/about/AboutPage.java

Start in about screen

---

src/main/java/de/qabel/desktop/ui/invite/InviteController.java
src/main/resources/de/qabel/desktop/ui/invite/invite.fxml
src/main/resources/ui.properties
src/main/resources/ui_de_DE.properties

and minor fix to invite view layout.

New invite text

---

src/main/resources/de/qabel/desktop/ui/accounting/identitycontextmenu/identitycontextmenu.fxml

hid disabled items in identityContextMenu

---

src/main/java/de/qabel/desktop/ui/remotefs/RemoteFSController.java

Added missing whitespace in delete dialog

---

src/main/resources/files/en/privacyNotes
src/main/resources/files/en/termsOfService

Previously, I only changed it in the setup. There have probably been multiple files to support styling in one version...now both are adjusted...

fixed terms and privacyPolicy in client itself

---

build.gradle
dependencies.lock

for #510 Received shares not usable without workaround

update core to 0.25.4

---

src/main/resources/de/qabel/desktop/ui/sync/sync.fxml

added scrollPane sync screen

---

installer/Dockerfile
installer/build-interactive.sh
installer/build-setup.sh

+added interactive build script to enter installer container

fixed installer for multi-module buld

---

CHANGELOG.md
client/src/main/java/de/qabel/desktop/daemon/sync/worker/DefaultSyncer.java

#532 prevent sync from recognizing parent dirs files

---

CHANGELOG.md
build.gradle
client/build.gradle
client/dependencies.lock
client/src/main/java/de/qabel/desktop/config/AccountSelectedEvent.kt
client/src/main/java/de/qabel/desktop/config/RepositoryBasedClientConfig.java
client/src/main/java/de/qabel/desktop/inject/NewConfigDesktopServiceFactory.java
client/src/main/java/de/qabel/desktop/inject/RuntimeDesktopServiceFactory.java
client/src/main/java/de/qabel/desktop/ui/accounting/login/LoginController.java
client/src/main/java/de/qabel/desktop/ui/accounting/login/LoginView.java
client/src/test/java/de/qabel/desktop/AsyncUtils.java
client/src/test/java/de/qabel/desktop/config/RepositoryBasedClientConfigTest.java
client/src/test/java/de/qabel/desktop/ui/AbstractControllerTest.java
gradle/wrapper/gradle-wrapper.properties
guiTest/src/test/java/de/qabel/desktop/ui/accounting/login/LoginControllerTest.kt
guiTest/src/test/java/de/qabel/desktop/ui/accounting/login/LoginGuiTest.java

depends on https://github.com/Qabel/qabel-core/pull/654
resolves #474

#474 use stored auth token and avoid password use if possible
